apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ca-service
  name: ca-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ca-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ca-service
    spec:
      containers:
        - args:
            - |
              echo "[INFO] Installazione di OpenSSL..."
              apt-get update && apt-get install -y openssl &&

              echo "[INFO] Generazione della Root CA..."
              mkdir -p /etc/ssl/iotronic &&
              cd /etc/ssl/iotronic &&

              openssl genrsa -out iotronic_CA.key 2048 &&
              openssl req -x509 -new -nodes -key iotronic_CA.key -sha256 -days 18250 \
                -subj "/C=IT/O=iotronic" -out iotronic_CA.pem &&

              echo "[INFO] Generazione della chiave privata e del certificato per Crossbar..."
              openssl genrsa -out crossbar.key 2048 &&
              openssl req -new -key crossbar.key -subj "/C=IT/O=iotronic/CN=crossbar" -out crossbar.csr &&
              openssl x509 -req -in crossbar.csr -CA iotronic_CA.pem -CAkey iotronic_CA.key -CAcreateserial -out crossbar.pem -days 18250 -sha256 &&

              echo "[INFO] Impostazione permessi certificati..."
              chmod 644 iotronic_CA.key iotronic_CA.pem crossbar.key crossbar.pem
              chmod 755 /etc/ssl/iotronic

              echo "[INFO] Certificati generati con successo."
              tail -f /dev/null
          command:
            - /bin/bash
            - -c
          image: debian:buster
          name: ca-service
          volumeMounts:
            - mountPath: /etc/ssl/iotronic
              name: iotronic-ssl
      restartPolicy: Always
      volumes:
        - name: iotronic-ssl
          persistentVolumeClaim:
            claimName: iotronic-ssl
