apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: iotronic-wstun
  name: iotronic-wstun
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: iotronic-wstun
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: iotronic-wstun
    spec:
      containers:
        - args:
            - |
              set -x  # DEBUG: Mostra i comandi eseguiti
              echo "[INFO] Verifica permessi certificati..."
              ls -l /var/lib/iotronic/ssl
              while [ ! -e /var/lib/iotronic/ssl/iotronic_CA.pem ] || [ ! -e /var/lib/iotronic/ssl/crossbar.key ]; do
                echo "[DEBUG] Certificati mancanti:"
                ls -l /var/lib/iotronic/ssl
                sleep 2
              done

              echo "[INFO] Certificati SSL trovati!"
              ls -l /var/lib/iotronic/ssl

              echo "[INFO] Avvio di iotronic-wstun..."
              exec node /usr/local/lib/node_modules/@mdslab/wstun/bin/wstun.js -r -s 8080 --ssl=true --key=/var/lib/iotronic/ssl/iotronic_CA.key --cert=/var/lib/iotronic/ssl/iotronic_CA.pem
          command:
            - /bin/sh
            - -c
          image: lucadagati/iotronic-wstun:latest
          name: iotronic-wstun
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 50001
              protocol: TCP
            - containerPort: 50002
              protocol: TCP
            - containerPort: 50003
              protocol: TCP
            - containerPort: 50004
              protocol: TCP
            - containerPort: 50005
              protocol: TCP
            - containerPort: 50006
              protocol: TCP
            - containerPort: 50007
              protocol: TCP
            - containerPort: 50008
              protocol: TCP
            - containerPort: 50009
              protocol: TCP
            - containerPort: 50010
              protocol: TCP
            - containerPort: 50011
              protocol: TCP
            - containerPort: 50012
              protocol: TCP
            - containerPort: 50013
              protocol: TCP
            - containerPort: 50014
              protocol: TCP
            - containerPort: 50015
              protocol: TCP
            - containerPort: 50016
              protocol: TCP
            - containerPort: 50017
              protocol: TCP
            - containerPort: 50018
              protocol: TCP
            - containerPort: 50019
              protocol: TCP
            - containerPort: 50020
              protocol: TCP
            - containerPort: 50021
              protocol: TCP
            - containerPort: 50022
              protocol: TCP
            - containerPort: 50023
              protocol: TCP
            - containerPort: 50024
              protocol: TCP
            - containerPort: 50025
              protocol: TCP
            - containerPort: 50026
              protocol: TCP
            - containerPort: 50027
              protocol: TCP
            - containerPort: 50028
              protocol: TCP
            - containerPort: 50029
              protocol: TCP
            - containerPort: 50030
              protocol: TCP
            - containerPort: 50031
              protocol: TCP
            - containerPort: 50032
              protocol: TCP
            - containerPort: 50033
              protocol: TCP
            - containerPort: 50034
              protocol: TCP
            - containerPort: 50035
              protocol: TCP
            - containerPort: 50036
              protocol: TCP
            - containerPort: 50037
              protocol: TCP
            - containerPort: 50038
              protocol: TCP
            - containerPort: 50039
              protocol: TCP
            - containerPort: 50040
              protocol: TCP
            - containerPort: 50041
              protocol: TCP
            - containerPort: 50042
              protocol: TCP
            - containerPort: 50043
              protocol: TCP
            - containerPort: 50044
              protocol: TCP
            - containerPort: 50045
              protocol: TCP
            - containerPort: 50046
              protocol: TCP
            - containerPort: 50047
              protocol: TCP
            - containerPort: 50048
              protocol: TCP
            - containerPort: 50049
              protocol: TCP
            - containerPort: 50050
              protocol: TCP
            - containerPort: 50051
              protocol: TCP
            - containerPort: 50052
              protocol: TCP
            - containerPort: 50053
              protocol: TCP
            - containerPort: 50054
              protocol: TCP
            - containerPort: 50055
              protocol: TCP
            - containerPort: 50056
              protocol: TCP
            - containerPort: 50057
              protocol: TCP
            - containerPort: 50058
              protocol: TCP
            - containerPort: 50059
              protocol: TCP
            - containerPort: 50060
              protocol: TCP
            - containerPort: 50061
              protocol: TCP
            - containerPort: 50062
              protocol: TCP
            - containerPort: 50063
              protocol: TCP
            - containerPort: 50064
              protocol: TCP
            - containerPort: 50065
              protocol: TCP
            - containerPort: 50066
              protocol: TCP
            - containerPort: 50067
              protocol: TCP
            - containerPort: 50068
              protocol: TCP
            - containerPort: 50069
              protocol: TCP
            - containerPort: 50070
              protocol: TCP
            - containerPort: 50071
              protocol: TCP
            - containerPort: 50072
              protocol: TCP
            - containerPort: 50073
              protocol: TCP
            - containerPort: 50074
              protocol: TCP
            - containerPort: 50075
              protocol: TCP
            - containerPort: 50076
              protocol: TCP
            - containerPort: 50077
              protocol: TCP
            - containerPort: 50078
              protocol: TCP
            - containerPort: 50079
              protocol: TCP
            - containerPort: 50080
              protocol: TCP
            - containerPort: 50081
              protocol: TCP
            - containerPort: 50082
              protocol: TCP
            - containerPort: 50083
              protocol: TCP
            - containerPort: 50084
              protocol: TCP
            - containerPort: 50085
              protocol: TCP
            - containerPort: 50086
              protocol: TCP
            - containerPort: 50087
              protocol: TCP
            - containerPort: 50088
              protocol: TCP
            - containerPort: 50089
              protocol: TCP
            - containerPort: 50090
              protocol: TCP
            - containerPort: 50091
              protocol: TCP
            - containerPort: 50092
              protocol: TCP
            - containerPort: 50093
              protocol: TCP
            - containerPort: 50094
              protocol: TCP
            - containerPort: 50095
              protocol: TCP
            - containerPort: 50096
              protocol: TCP
            - containerPort: 50097
              protocol: TCP
            - containerPort: 50098
              protocol: TCP
            - containerPort: 50099
              protocol: TCP
            - containerPort: 50100
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/iotronic/ssl
              name: iotronic-ssl
      restartPolicy: Always
      volumes:
        - name: iotronic-ssl
          persistentVolumeClaim:
            claimName: iotronic-ssl
