apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: iotronic-db
  name: iotronic-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: iotronic-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: iotronic-db
    spec:
      containers:
        - args:
            - mysqld
            - --bind-address=0.0.0.0
            - --max_connections=4096
            - --collation-server=utf8_general_ci
            - --character-set-server=utf8
            - --innodb-buffer-pool-size=1G
            - --innodb-flush-log-at-trx-commit=1
            - --innodb-file-per-table=1
          env:
            - name: MYSQL_DATABASE
              value: unime
            - name: MYSQL_PASSWORD
              value: s4t
            - name: MYSQL_ROOT_PASSWORD
              value: unime
            - name: MYSQL_USER
              value: admin
          image: mariadb:focal
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -punime
            failureThreshold: 5
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
          name: iotronic-db
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: unime-iotronic-db-data
      restartPolicy: Always
      volumes:
        - name: unime-iotronic-db-data
          persistentVolumeClaim:
            claimName: unime-iotronic-db-data
