apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: iotronic-wagent
  name: iotronic-wagent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: iotronic-wagent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: iotronic-wagent
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - |2-
                echo '[INFO] Configurazione dei permessi sui log...';
                chown -R iotronic:iotronic /var/log/iotronic;
                echo '[INFO] Avvio del Wagent...';
                exec /usr/local/bin/iotronic-wamp-agent --config-file /etc/iotronic/iotronic.conf
          env:
            - name: DB_CONNECTION_STRING
              value: mysql+pymysql://iotronic:unime@iotronic-db/iotronic
            - name: DB_HOST
              value: iotronic-db
            - name: MYSQL_ROOT_PASSWORD
              value: s4t
            - name: OS_AUTH_URL
              value: http://keystone:5000/v3
            - name: OS_PASSWORD
              value: s4t
            - name: OS_PROJECT_DOMAIN_NAME
              value: Default
            - name: OS_PROJECT_NAME
              value: admin
            - name: OS_USERNAME
              value: admin
            - name: OS_USER_DOMAIN_NAME
              value: Default
          image: lucadagati/iotronic-wagent:latest
          name: iotronic-wagent
          volumeMounts:
            - mountPath: /etc/iotronic
              name: iotronic-wagent-cm0
            - mountPath: /var/log/iotronic
              name: iotronic-logs
      restartPolicy: Always
      volumes:
        - configMap:
            name: iotronic-wagent-cm0
          name: iotronic-wagent-cm0
        - name: iotronic-logs
          persistentVolumeClaim:
            claimName: iotronic-logs
