apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: lightning-rod
  name: lightning-rod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lightning-rod
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: lightning-rod
    spec:
      containers:
        - args:
          - |
            sed -i 's|self\.wstun_ip *= *urlparse(board\.wamp_config\["url"\])\[1\]\.split('\'':'\'')\[0\]|self.wstun_ip = "iotronic-wstun"|' /usr/local/lib/python3*/site-packages/iotronic_lightningrod/modules/service_manager.py
            exec startLR
          command:
            - /bin/sh
            - -c
          image: lucadagati/lrod:compose
          name: lightning-rod
          ports:
            - containerPort: 1474
              protocol: TCP
          securityContext:
            privileged: true
          stdin: true
          tty: true
      restartPolicy: Always